# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

$production_package_name = "com.example.example_app"
$development_package_name = $production_package_name + ".develop"
$parent_directory = File.expand_path("..", Dir.pwd)

default_platform(:android)

platform :android do
  desc "Change the package name of the project"
  lane :change_package_name do |options|
    
    new_package_name = options[:new_package_name]
    if new_package_name.nil? || new_package_name.to_s.empty?
      new_package_name = $production_package_name
    end

    # Change the package name output to change between
    # development and production builds
    rename_package_name(
      project_home_path: $parent_directory,
      new_package_name: new_package_name,
      platform: "android",
      profiles: ["main", "debug", "profile"]
    )

    # Do any additional stuff.
  end
end
